### ISSUE TITLE
Random ids cause snapshot based testing to fail

### ISSUE THREAD

**Issue by mrchief** [icarus-sullivan/react-spinner-material#11]
https://github.com/icarus-sullivan/react-spinner-material/blob/master/src/helpers.js#L84 causes a random id which causes snapshot updates - leading to test failures.

![image](https://user-images.githubusercontent.com/781818/40513661-74058d90-5f74-11e8-98d4-b70a98c34996.png)

At a glance, I think the whole `id` assignment can be skipped but I might be overlooking things.

At a minimum, if the id generation can be made deterministic, this won't be an issue.

**Comment by icarus-sullivan** [comment]
Hey @mrchief Thanks for letting me know, sorry I didn't see this until recently I was on vacation. 

The unique id's are there so you can use multiple spinners without them modifying the original Spinner. It is being generated with Date.now() so you can do something like the following 

```
Date.now = jest.fn(() => 1000); 
```

Or we can modify it to use a number starting from 0 and increment for every new spinner added. 

i.e. spinner_0, spinner_1, ...

**Comment by mrchief** [comment]
I would vote for the later approach. Monkey patching a global object sounds problematic..

**Comment by icarus-sullivan** [comment]
Mocking Date in jest has been a thing for a while, however, I'll look into making it more deterministic. 

https://facebook.github.io/jest/docs/en/snapshot-testing.html#2-tests-should-be-deterministic

**Comment by mrchief** [comment]
You assume everyone uses jest. 🙂

**Comment by icarus-sullivan** [comment]
@mrchief Its not the prettiest solution, and sorry it took so long (life gets busy). But [I have added](https://github.com/icarus-sullivan/react-spinner-material/commit/5d2646dcc22df871cb50fafae87108c850fb249d) a simple deterministic id for the component.

**Comment by mrchief** [comment]
This is simple and functional. And this will work, so thanks for adding this.

Curious though, why `ID_HOLDER.id` and not just `id`?

**Comment by icarus-sullivan** [comment]
@mrchief It could probably be done with a single id variable. However using something like an object property ensures that the id will remain the same even if it is re-imported. This is based on the assumption that javascript hoist the module in a strict manner. i.e. `window.DATA_HOLDER` would already exist so it is not reconstructed/reassigned globally. Whereas a local variable would use local scope and reset to the value of 0 when imported. 

Again, this is an assumption that I am inferring when following `Secrets of a Javscript Ninja` and how variables are assigned for scope globally and locally. I may be wrong but it seems more likely the object will stick around longer than a local variable.
