### ISSUE TITLE
TypeScript error (TS2605) occurred in 1.1.2

### ISSUE THREAD

**Issue by orrisroot** [icarus-sullivan/react-spinner-material#12]
Hi, I'd like to report a problem of latest version 1.1.2 with typescript.

react: 16.9.0 (@types/react 16.9.2)
react-dom: 16.9.0 (@types/react-dom 16.8.5)
typescript: 3.5.3
react-spinner-material: 1.1.2

```
 TypeScript error in ....(xxx,xxx):
 JSX element type 'false | Element' is not a constructor function for JSX elements.
  Type 'false' is not assignable to type 'Element | null'.  TS2605
```

It seems that Spinner component should not return false.

**Comment by icarus-sullivan** [comment]
You're right, I changed it to be a shorthand conditional. Will update it

**Comment by icarus-sullivan** [comment]
@orrisroot Just published a fix https://www.npmjs.com/package/react-spinner-material

Let me know if you experience any more issues.

**Comment by orrisroot** [comment]
@icarus-sullivan Thank you for your fast response!
When I updated to the new version, the problem was solved and it works fine!
Thank you again,
