### ISSUE TITLE
License needed

### ISSUE THREAD

**Issue by iheart2code** [icarus-sullivan/react-spinner-material#3]
You need to select a license if you want anyone to make use of this.

**Comment by iheart2code** [comment]
I actually see in your package.json you've selected Apache 2.0. You might want to make that a bit more obvious by including a license file or something.

**Comment by icarus-sullivan** [comment]
Thanks, thought I selected the Unlicense but I'll update it when I get home

**Comment by iheart2code** [comment]
Thanks. Would love to use this for a project -- it looks great!

**Comment by icarus-sullivan** [comment]
I can update it on githun right now, but it won't show it in npm until I
update.

That sound good??

**Comment by iheart2code** [comment]
Yeah. I just made a PR for you.
