### ISSUE TITLE
1.0.14 build error Can't resolve './index.css' 

### ISSUE THREAD

**Issue by ACOSW** [icarus-sullivan/react-spinner-material#8]
Greetings!
Last version of react-spinner-material (1.0.14) breaks webpack build.
Here is error:
`ERROR in ./~/react-spinner-material/lib/index.js
Module not found: Error: Can't resolve './index.css' in '***/node_modules/react-spinner-material/lib'
 @ ./~/react-spinner-material/lib/index.js 17:0-22`

**Comment by gristoi** [comment]
yup, got exactly same issue here, just blown up our dev build

**Comment by icarus-sullivan** [comment]
Updated the library last night but forgot to add a param to the build script. 

Can you try v1.0.14-beta and let me know if you see any problems?

**Comment by ACOSW** [comment]
@icarus-sullivan confirm, latest release fixed build. Thanks for fast feedback.
Now we have new problem while using css modules. 
As temporary solution i use custom loading options in my code:
`import '!style-loader!css-loader?modules=false!react-spinner-material/lib/index.css';`

**Comment by icarus-sullivan** [comment]
Injected the styles into the head of a document (if it exists) when the lib is loaded. 

Newest version is 1.0.15. 

Sorry for the late update again, been head down at work :/
