### ISSUE TITLE
Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by dixonbegay** [icarus-sullivan/react-spinner-material#9]
React version: 15.6.1
react-spinner-material version: 1.0.15

Getting warning in console of developer tools...
```
Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in React
v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage,
compatibility, migration and more, see https://fb.me/prop-types-docs
```

The [prop-types](https://www.npmjs.com/package/prop-types) package is required when v16 of React releases.

**Comment by icarus-sullivan** [comment]
I am currently on vacation but will return by August 19th.
